### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [JunchuanWang80/Crossline#3]
I would like to point out that an identifier like “[`__CROSSLINE_H`](https://github.com/jcwangxp/Crossline/blob/c8bd447d8e52d11e19b39060f393236610d457d2/crossline.h#L36 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jcwangxp** [comment]
This is not an issue, and the naming is consistent with [linenoise.h](https://github.com/antirez/linenoise/blob/master/linenoise.h)

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid that software components [depend on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?").
