### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [JunchuanWang80/Crossline#4]
Would you like to add more error handling for return values from functions like the following?
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [crossline_cursor_set](https://github.com/jcwangxp/Crossline/blob/c8bd447d8e52d11e19b39060f393236610d457d2/crossline.c#L632)
* [sigaction](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action") ⇒ [crossline_winchg_reg](https://github.com/jcwangxp/Crossline/blob/c8bd447d8e52d11e19b39060f393236610d457d2/crossline.c#L1036)

**Comment by jcwangxp** [comment]
There're nice to have, will consider later, thanks.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
