### ISSUE TITLE
Completion support with C++

### ISSUE THREAD

**Issue by kiwichris** [JunchuanWang80/Crossline#7]
I would like to be able to use completion support with C++ however the completion callback does not have a user argument. If I could pass the `this` pointer of an object as `user` data I could integrate completion into my C++ program.

I am thinking about adding a new callback type and call to maintain backwards compatibility:
```c
typedef void (*crossline_user_completion_callback) (void* user, const char *buf, crossline_completions_t *pCompletions);
extern void  crossline_user_completion_register (crossline_user_completion_callback pCbFunc, void* user);
```
If a `crossline_user_completion_callback` is registered it is called else the `crossline_completion_callback` is called if registered.

Would you be interested in a pull request for such a change?

**Comment by jcwangxp** [comment]
In fact, the callback prototype is copied from famous [linenoise.h](https://github.com/antirez/linenoise/blob/master/linenoise.h)
As you can only register one callback, if you want to pass extra arg, you can use a static or global variable and refer it in the callback.

**Comment by kiwichris** [comment]
Thanks for getting back to me. I would prefer not to use statics. The change would not change the existing interface, it would add a new one.
